version: "3.9"

services:
  db:
    restart: always
    container_name: mysql
    image: mysql:5.7
    build: ./MySQLContainer
    network_mode: "bridge"
    ports:
    - 3307:3306
    expose:
      - '3307'
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: abernathyclinic
      MYSQL_PASSWORD: rootroot
